[pytest]
DJANGO_SETTINGS_MODULE = config.settings.dev
python_files = tests.py test_*.py
testpaths = src/apps
addopts =
    --strict-markers
    --tb=short
    -p no:warnings
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
